name: initialize reeco

on: [push]
  # schedule:
  #   - cron: '25 9 * * *' # '0 0 * * 1' At 00:00 on Monday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed

      - name: check if repositories.txt exists in this repo
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "repositories.txt"

      - name: repositories.txt exists, read content
        if: steps.check_files.outputs.files_exists == 'true'
        id: read_content
        uses: juliangruber/read-file-action@v1
        with:
          path: ./repositories.txt

      - name: Echo repositories.txt
        if: ${{ success() }} #contains(steps.read_content.outputs.content,'github')
        run: echo "${{ steps.read_content.outputs.content }}"

      - name: repositories.txt does not exist, check if an issue already exists
        if: steps.check_files.outputs.files_exists == 'false'
        uses: nickderobertis/check-if-issue-exists-action@master
        id: check_if_issue_exists
        with:
          repo: ${{secrets.MY_REPO}}
          token: ${{ secrets.MY_TOKEN }}
          title: missing repositories.txt
          labels: bug

      - name: repositories.txt and issue do not exist, create issue
        if: steps.check_if_issue_exists.outputs.exists == 'false'
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with:
          filename: .github/initialize.md

# todo : check if an issue already exists before opening a new one!

# todo
# - name: install python packages
#   run: |
#     python -m pip install --upgrade pip
#     pip install -r requirements.txt
# - name: execute py script # run main.py
#   run: python initialize.py
